#!/usr/bin/env python3
"""
=== NoemaForge File Header ===
File: noemaforge/src/readinglist_workflow.py
Zone: release/package
Version: 0.31.13.alpha
Created: 2026-05-14
Modified: 2026-05-14
Purpose: Provide NoemaForge release functionality for the packaged local runtime.
Inputs: Command-line arguments, environment variables, package files and local NoemaForge runtime state as applicable.
Outputs: Structured command output, files, service state or UI state as documented by the caller.
Side effects: Limited to the documented NoemaForge paths, runtime state directories or systemd units used by this file.
Tests: Syntax validation plus the release setup selftest, consistency-audit and targeted smoke checks.
Notes: Code comments are English-only; user-facing localized text belongs in docs/i18n or locale JSON files.
=== End NoemaForge File Header ===
"""
from __future__ import annotations

# === NoemaForge Autodoc File Header ===
# File: src/readinglist_workflow.py
# Purpose: Turn browser/tabs ingest data into a normalized reading queue with dedupe and review states.
# Invoked by / imported from:
#   - tests/test_workflow_modules.py
# Public API / entry functions:
#   - build_queue
# Inputs:
#   - tabs_index.sqlite generated by tools/prep/scan_tabs.py.
# Output formats / side effects:
#   - JSON and Markdown reading-queue artifacts.
# AutoDoc: refreshed 2026-04-11 (manual)
# === End NoemaForge Autodoc File Header ===


import json
import os
import sqlite3
import urllib.parse
from typing import Any, Dict, List


def _norm_url(url: str) -> str:
    try:
        p = urllib.parse.urlsplit(url)
        return urllib.parse.urlunsplit((p.scheme, p.netloc.lower(), p.path, '', ''))
    except Exception:
        return url


def build_queue(db_path: str, out_dir: str, limit: int = 500) -> Dict[str, Any]:
    os.makedirs(out_dir, exist_ok=True)
    con = sqlite3.connect(db_path)
    con.row_factory = sqlite3.Row
    rows = con.execute('SELECT url, title, source_file, added_at, last_seen_at, status FROM tabs ORDER BY last_seen_at DESC LIMIT ?', (int(limit),)).fetchall()
    con.close()

    seen = set()
    items: List[Dict[str, Any]] = []
    for row in rows:
        url = _norm_url(str(row['url'] or '').strip())
        if not url or url in seen:
            continue
        seen.add(url)
        items.append({
            'url': url,
            'title': str(row['title'] or '').strip(),
            'added_at': row['added_at'],
            'last_seen_at': row['last_seen_at'],
            'source_file': row['source_file'],
            'queue_state': 'review',
        })

    json_path = os.path.join(out_dir, 'reading_queue.json')
    md_path = os.path.join(out_dir, 'reading_queue.md')
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump({'ok': True, 'items': items}, f, ensure_ascii=False, indent=2)
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write('# Reading queue\n\n')
        for item in items:
            f.write(f"- [review] {item['title'] or item['url']} :: {item['url']}\n")
    return {'ok': True, 'count': len(items), 'json_path': json_path, 'markdown_path': md_path}


def build_reading_queue(*, index_db: str, out_dir: str, limit: int = 500) -> Dict[str, Any]:
    return build_queue(index_db, out_dir, limit=limit)
