#!/usr/bin/env python3
"""
=== NoemaForge File Header ===
File: noemaforge/src/tg_channel_workflow.py
Zone: release/package
Version: 0.31.13.alpha-patched1
Created: 2026-05-14
Modified: 2026-05-14
Purpose: Provide NoemaForge release functionality for the packaged local runtime.
Inputs: Command-line arguments, environment variables, package files and local NoemaForge runtime state as applicable.
Outputs: Structured command output, files, service state or UI state as documented by the caller.
Side effects: Limited to the documented NoemaForge paths, runtime state directories or systemd units used by this file.
Tests: Syntax validation plus the release setup selftest, consistency-audit and targeted smoke checks.
Notes: Code comments are English-only; user-facing localized text belongs in docs/i18n or locale JSON files.
=== End NoemaForge File Header ===
"""
from __future__ import annotations

# === NoemaForge Autodoc File Header ===
# File: src/tg_channel_workflow.py
# Purpose: Turn Telegram export indexes into curated reviewable workflow artifacts with normalization, dedupe, and fact-check cues.
# Invoked by / imported from:
#   - tests/test_workflow_modules.py
# Public API / entry functions:
#   - curate_from_index
# Inputs:
#   - tg_index.sqlite generated by tools/prep/scan_tg.py.
# Output formats / side effects:
#   - JSON and Markdown curated-review artifacts.
# Security considerations:
#   - Uses already-scrubbed text_clean values and never re-emits raw original exports.
# AutoDoc: refreshed 2026-04-11 (manual)
# === End NoemaForge Autodoc File Header ===


import hashlib
import json
import os
import sqlite3
from typing import Any, Dict, List


def _score_item(text: str, links: int) -> int:
    score = 0
    if '?' in text:
        score += 2
    if links:
        score += 3
    if len(text) > 180:
        score += 1
    if 'http' in text:
        score += 1
    return score


def curate_from_index(db_path: str, out_dir: str, limit: int = 200) -> Dict[str, Any]:
    os.makedirs(out_dir, exist_ok=True)
    con = sqlite3.connect(db_path)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        """
        SELECT m.chat_id, m.msg_id, m.date, m.sender, m.text_clean,
               COUNT(l.url) AS link_count
        FROM messages m
        LEFT JOIN links l ON l.chat_id = m.chat_id AND l.msg_id = m.msg_id
        GROUP BY m.chat_id, m.msg_id, m.date, m.sender, m.text_clean
        ORDER BY m.date DESC
        LIMIT ?
        """,
        (int(limit),),
    ).fetchall()
    con.close()

    seen = set()
    items: List[Dict[str, Any]] = []
    for row in rows:
        text = str(row['text_clean'] or '').strip()
        if not text:
            continue
        digest = hashlib.sha256(text.lower().encode('utf-8')).hexdigest()
        if digest in seen:
            continue
        seen.add(digest)
        link_count = int(row['link_count'] or 0)
        items.append({
            'chat_id': row['chat_id'],
            'msg_id': row['msg_id'],
            'date': row['date'],
            'sender': row['sender'],
            'text': text,
            'link_count': link_count,
            'score': _score_item(text, link_count),
            'fact_check_needed': bool(link_count or '?' in text),
            'review_status': 'new',
        })

    items.sort(key=lambda x: (-int(x.get('score') or 0), str(x.get('date') or '')), reverse=False)
    json_path = os.path.join(out_dir, 'tg_curated_items.json')
    md_path = os.path.join(out_dir, 'tg_curated_items.md')
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump({'ok': True, 'items': items}, f, ensure_ascii=False, indent=2)
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write('# Curated Telegram items\n\n')
        for item in items:
            f.write(f"- [{item['review_status']}] score={item['score']} fact_check={item['fact_check_needed']} :: {item['text'][:180]}\n")
    return {'ok': True, 'count': len(items), 'json_path': json_path, 'markdown_path': md_path}


def curate_channel(*, index_db: str, out_dir: str, limit: int = 200) -> Dict[str, Any]:
    return curate_from_index(index_db, out_dir, limit=limit)
